name: Generate Model List and Docs
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-model-list:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: '.github/.generate/package-lock.json'

      - name: Install dependencies
        shell: bash
        working-directory: .github/.generate
        run: npm ci

      - name: Generate model list
        shell: bash
        working-directory: .github/.generate
        run: npm run model-list
        env:
          INPUT_OPEN-ROUTER-KEY: ${{ secrets.OPENROUTER_API_KEY }}
          INPUT_DEEPL-KEY: ${{ secrets.DEEPL_API_KEY }}
          INPUT_OPEN-AI-KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit and push version update
        id: commit_and_push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add models.json
          git add models.hashes.json
          git commit -m "Updated models.json after upstream changes [skip ci]"
          git push
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Dump swagger file
        shell: bash
        working-directory: .github/.generate
        run: npm run swagger

      - name: Prepare pages directory
        id: pages
        working-directory: .github/.generate
        run: npm run prepare-pages

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.pages.outputs.pages-dir }}

  deploy:
    name: Deploy to GitHub Pages
    needs: update-model-list
    if: github.ref == 'refs/heads/main'

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
